import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const generatedPath = join(repoRoot, "docs", "generated", "package-index.md");

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function workspaceDirs(group) {
  const root = join(repoRoot, group);
  if (!existsSync(root)) {
    return [];
  }

  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(root, entry.name))
    .filter((dir) => existsSync(join(dir, "package.json")))
    .sort((a, b) => a.localeCompare(b));
}

function packageRow(dir) {
  const manifest = readJson(join(dir, "package.json"));
  const repoPath = relative(repoRoot, dir).replaceAll("\\", "/");
  const readmePath = join(dir, "README.md");
  const readmeLink = existsSync(readmePath) ? `[README](../../${repoPath}/README.md)` : "";
  const publishStatus = manifest.private === true ? "private" : "public";

  return {
    name: manifest.name,
    path: repoPath,
    publishStatus,
    description: manifest.description ?? "",
    readmeLink,
  };
}

const packages = workspaceDirs("packages").map(packageRow);
const examples = workspaceDirs("examples").map(packageRow);

const lines = [
  "# Generated Package Index",
  "",
  "This file is generated by `npm run docs`. Do not edit it by hand.",
  "",
  "## Packages",
  "",
  "| Name | Path | Publish | Description | Docs |",
  "| --- | --- | --- | --- | --- |",
  ...packages.map(
    (pkg) =>
      `| \`${pkg.name}\` | \`${pkg.path}\` | ${pkg.publishStatus} | ${pkg.description} | ${pkg.readmeLink} |`,
  ),
  "",
  "## Examples",
  "",
  "| Name | Path | Publish | Description | Docs |",
  "| --- | --- | --- | --- | --- |",
  ...examples.map(
    (pkg) =>
      `| \`${pkg.name}\` | \`${pkg.path}\` | ${pkg.publishStatus} | ${pkg.description} | ${pkg.readmeLink} |`,
  ),
  "",
];

const next = `${lines.join("\n")}\n`;

if (checkOnly) {
  if (!existsSync(generatedPath)) {
    console.error(`Generated docs are missing: ${relative(repoRoot, generatedPath)}`);
    process.exit(1);
  }

  const current = readFileSync(generatedPath, "utf8");
  if (current !== next) {
    console.error("Generated docs are out of date. Run `npm run docs`.");
    process.exit(1);
  }

  console.log("Generated docs are current.");
} else {
  mkdirSync(dirname(generatedPath), { recursive: true });
  writeFileSync(generatedPath, next);
  console.log(`Wrote ${relative(repoRoot, generatedPath)}`);
}
